<h1>Numpy Array Indexing and Selection</h1>

In [5]:
import numpy as np

In [6]:
arr = np.arange(0,11)

In [7]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

<h3> Index and Slicing</h3>

In [8]:
arr[8]  # Select the value at index 8

8

In [9]:
arr[1:5] # Start at index  1 and end at index 4

array([1, 2, 3, 4])

In [10]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [11]:
arr[:6]  # Get everything up to index 6, using :

array([0, 1, 2, 3, 4, 5])

In [12]:
arr[5:]             # Get everything starting from index position 5 onto the end of the list

array([ 5,  6,  7,  8,  9, 10])

<h3>Broadcasting</h3>

In [13]:
arr[0:5] = 100      # This will broadcast the first five values to be 100 in the list

In [14]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [15]:
arr = np.arange(0,11)

In [16]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

<h3>Copying</h3>

In [17]:
slice_of_arr = arr[0:6]

In [18]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [19]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
arr_copy = arr.copy()   # .COPY()
                        # Copy data from an existing array into another array,
                        # to preserve the original data

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
arr_copy[:] = 100      # Change the values in arr_copy via broadcasting to 100

In [28]:
arr_copy             # The value of arr_copy contains all 100s

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [29]:
arr                 # The array arr has the original data 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

<h3>Indexing a 2-D array (Matrix)</h3>

In [32]:
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])      # 2-D array with a nested list. (Lists inside of a list)

In [33]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [39]:
arr_2d[0][0]                    # Double bracket Format for grabbing Data
                                # To get the value 5, first grab at index [0], which is the first row,
                                # next, grab at index[0] again to grab the first value in the first column

5

In [41]:
arr_2d[0]                       # Returns the entire first row

array([ 5, 10, 15])

In [42]:
arr_2d[1][1]                   # To grab value 25

25

In [43]:
arr_2d[2][1]                   # To grab value 40

40

In [49]:
arr_2d[2,1]                     # Single Bracket Notation (Recommended)
                                # Uses comma notation

40

In [46]:
arr_2d[1,1]                  

25

In [47]:
arr_2d[0,0]

5

In [48]:
arr_2d[1,2]

30

<h4> Grabbing Sections of an Array</h4>

In [53]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [50]:
arr_2d[:2,1:]   # Grab from the top right corner 10,15 and 35,30
                # First, grab everything up to row 2 using :2,
                # Then grab everything from column 1 all the way to the end, using 1:

array([[10, 15],
       [25, 30]])

In [51]:
arr_2d[:2]      # Grab the first two rows only, not the 3rd row.

array([[ 5, 10, 15],
       [20, 25, 30]])

In [56]:
arr_2d[1:,1:]   # Grab 25,30 and 40,45
                # Skip the first row, using 1:, (which returns [20, 25, 30], [35, 40, 45])
                # then skip the first column, using 1:, (which returns 25, 40, 30,45)

array([[25, 30],
       [40, 45]])

In [60]:
arr_2d[:2,:2]   # Grab 5,10 and 20,25
                # Skip the last row, using :2 (which returns 5,10,15 and 20,25,30)
                # Then, skip the last column using :2 (which returns 5,10 and 20,25)

array([[ 5, 10],
       [20, 25]])

<h3>Conditional Selections</h3>

In [61]:
arr = np.arange(1,11)

In [62]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
bool_arr = arr > 5          # Compare the array to return a BOOLEAN result
                            # This example compares to see if values in arr are greater than 5

In [67]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [70]:
arr[bool_arr]               # Conditionally Selecting elements from the arr array
                            # This returns only the True values from the bool_arr variable

array([ 6,  7,  8,  9, 10])

In [71]:
arr[arr > 5]                # Putting this into one step.
                            # Returns the elements that are TRUE from the boolean comparsion, greater than 5

array([ 6,  7,  8,  9, 10])

In [72]:
arr[arr < 3]                # Find all the elements of the array arr which are less than 3.

array([1, 2])

<h3> Grabbing Array Sections Practice</h3>

In [75]:
arr_2d = np.arange(50).reshape(5,10)        # Create a range of 50 numbers
                                            # Reshape as a 5x10 array
                                            # Assign to variable arr_2d

In [76]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [86]:
arr_2d[1:3,3:5]                                  # Grab 13,14 and 23,24

array([[13, 14],
       [23, 24]])

In [88]:
arr_2d[2:4,8:]                                  # Grab 28,29 and 38,39

array([[28, 29],
       [38, 39]])

In [91]:
arr_2d[1:4,7:9]                                 # Grab 17,18 and 27,28 and 37,38

array([[17, 18],
       [27, 28],
       [37, 38]])

In [96]:
arr_2d[3:,1:4]                                 # Grab 31 - 33, and 41 - 43 

array([[31, 32, 33],
       [41, 42, 43]])